@startuml
left to right direction
actor Member as M
actor User as U
package Application {
  usecase " se loguer" as SL
  usecase "deconnection" as D
  usecase "s'enregistrer" as E

  usecase "creation d'une figure" as CF

  usecase "ajout d'une image" as AI
  usecase "modification de l'image" as MI
  usecase "suppression de l'image" as SI
  usecase "ajout d'une video" as AV
  usecase "modification de la video" as MV
  usecase "suppression de la video" as SV

  usecase "Modifier la figure" as FM
  usecase "supprimer la figure" as SF
  usecase "mettre un commentaire" as MC
  usecase "consulter les figures" as LF
  usecase "supprimer le commentaire" as SC

}
M-->SL
M-->D
M-->AI
M-->MI
M-->SI
M-->AV
M-->MV
M-->SV
M-->FM
M-->SF
M-->CF
M-->MC
M-->SC
U-->LF
U->E
M-|>U
@enduml