@startuml

title Sequence : Add figure

actor Members as U
participant Controller as C
participant Doctrine as D
participant repository as REPO
participant SGBD as BDD
ref over U,C,D,BDD : Connection

U->C:  new figure
C->D:Request
activate D
D->BDD: insertion in the bdd
destroy BDD
deactivate D
C->REPO: request
activate REPO
REPO-->C: reponse
deactivate REPO
C-->U:affichage de la nouvelle figure

@enduml